### ISSUE TITLE
led NOT RUNNING

### ISSUE THREAD

**Issue by Doanduy09** [NONGFAH/luci-app-athena-led#1]
I installed and it did not run the option zonename 'asia/ho chi minh'
 It only works in the UTC secret mode, hope you fix it soon. Thank you
You can integrate led control into luci build rom, it's great

**Comment by NONGFAH** [comment]
Configure the time zone of the OpenWRT system, and then restart the program.

**Comment by Doanduy09** [comment]
I also tried as you said but it didn't work, if I choose Bangkok time zone it works... only Ho Chi Minh time zone has an error...

**Comment by NONGFAH** [comment]
This bug has been fixed，you can pull the code and build it by yourself

[athena-led](https://github.com/NONGFAH/athena-led)

**Comment by Doanduy09** [comment]
I also tried as you said but it didn't work, if I choose Bangkok time has an error.... only Ho Chi Minh time zone has an error...I have restarted my computer many times but it still doesn't work.
![Screenshot (606)](https://github.com/user-attachments/assets/299e5309-0199-48c8-8ddf-a429a349c9a3)
